services:
  - type: web
    name: findit-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/FindIt-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: 8080

databases:
  - name: findit-db
    databaseName: findit
    user: findit 